version: '3.3'
services:
  app:
    build: .
    ports:
      - "80:3001"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/celebration
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
